mongodb:
  dpname: mongo-deployment
  name: mongodb
  image: mongo
  tag: latest
  replicas: 1
  service:
    name: mongodb
    port: 27017
   
express:
  name: mongo-express
  image: mongo-express
  tag: latest
  replicas: 2
  service:
    port: 8081
    targetPort: 8081
    nodePort: 32000
