apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mongo-k8s-demo
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        # The GitHub organization or user.
        owner: saurabh3460
        # The Github repository
        repo: mongo-k8s-demo
        # For GitHub Enterprise (optional)
        # api: https://git.example.com/
        # Reference to a Secret containing an access token. (optional)
        tokenRef:
          secretName: github-token
          key: token
        # (optional) use a GitHub App to access the API instead of a PAT.
        # appSecretName: github-app-repo-creds
        # Labels is used to filter the PRs that you want to target. (optional)
        labels:
        - preview
      requeueAfterSeconds: 1800
  template:
    metadata:
      name: 'pr-{{branch}}-{{number}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/saurabh3460/mongo-k8s-demo
        targetRevision: dev
        path: app
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      destination:
        server: https://kubernetes.default.svc
        namespace: 'bgd-{{branch}}-{{number}}'