apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels: 
    app: mongodb
    type: database
    for: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      
  template:
    metadata:
      labels: 
        app: mongodb
    spec:
      containers:
        - image:  mongo
          name:  mongodb
          ports:
            - containerPort:  27017
          env:
            - name:  MONGO_INITDB_ROOT_USERNAME                    
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-password                                              # use secret 

---
apiVersion: v1
kind: Service
metadata:
  name:  mongo-service
spec:
  selector:
    app: mongodb
  type:   ClusterIP 
  ports:
  - protocol: TCP
    port:  27017
    targetPort:  27017