apiVersion: v1
kind: Secret
metadata:
  name:  mongo-secret
type: Opaque
data:
   #secretKey:  BASE64_ENCODED_VALUE
   mongo-root-username: {{.Values.username}}
   mongo-root-password: {{.Values.password}}