apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.express.name}}
  labels: 
    app: {{.Values.express.name}}
spec:
  replicas: {{.Values.express.replicas}}
  selector:
    matchLabels:
      app: {{.Values.express.name}}
  template:
    metadata:
      labels:
        app: {{.Values.express.name}}
    spec:
      containers:
      - name: {{.Values.express.name}}
        image: {{.Values.express.image}}:{{.Values.express.tag}}
        ports:
        - containerPort: 8081 
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME 
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-username

        - name: ME_CONFIG_MONGODB_ADMINPASSWORD 
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-password

        - name:  ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongo-configmap
              key: database_url      
        # - name: ME_CONFIG_BASICAUTH_USERNAME    
        # - name: ME_CONFIG_BASICAUTH_PASSWORD    
        # - name: ME_CONFIG_MONGODB_ENABLE_ADMIN  
---
kind: Service
apiVersion: v1
metadata:
  name:  {{.Values.express.name}}
spec:
  selector:
    app:  {{.Values.express.name}}
  type: LoadBalancer
  ports:  
  - port:  {{.Values.express.service.port}}
    targetPort:  {{.Values.express.service.targetPort}}
    nodePort: {{.Values.express.service.nodePort}}