apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.mongodb.dpname}}
  labels: 
    app: {{.Values.mongodb.name}}
    type: database

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.mongodb.name}}
      
  template:
    metadata:
      labels: 
        app: {{.Values.mongodb.name}}
    spec:
      containers:
        - image:  {{.Values.mongodb.image}}:{{.Values.mongodb.tag}}
          name:  {{.Values.mongodb.name}}
          ports:
            - containerPort:  27017
          env:
            - name:  MONGO_INITDB_ROOT_USERNAME                    
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-password                                              # use secret 

---
apiVersion: v1
kind: Service
metadata:
  name:  {{.Values.mongodb.service.name}}
spec:
  selector:
    app: {{.Values.mongodb.name}}
  type:   ClusterIP 
  ports:
  - protocol: TCP
    port:  {{.Values.mongodb.service.port}}
    targetPort:  27017