apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ required "A valid .Values.mongodb.dpname entry required!" .Values.dpname}}
  labels: 
    app: {{.Values.name}}
    type: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels: 
        app: {{.Values.name}}
    spec:
      containers:
        - image:  {{.Values.image}}:{{.Values.tag}}
          name:  {{.Values.name}}
          ports:
            - containerPort:  27017
          env:
            - name:  MONGO_INITDB_ROOT_USERNAME                    
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-password # use secret 
---
apiVersion: v1
kind: Service
metadata:
  name:  {{.Values.service.name}}
spec:
  selector:
    app: {{.Values.name}}
  type:   ClusterIP 
  ports:
  - protocol: TCP
    port:  {{.Values.service.port}}
    targetPort:  27017